services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./config:/home/node/dist/cfg:ro
  worker:
    build: ./worker
    volumes:
      - ./config:/cfg:ro
  asp.net:
    build: ./signalRServer
    ports:
      - 5500:5500
    volumes:
      - ./config:/app/cfg:ro